#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    REPO = 'ctags-langserver'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    NODE_VERSION="10"
    YARN_GPG = 'no'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '20'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }
  parameters {
    booleanParam(name: 'PUBLISH_TO_NPM', defaultValue: false, description: 'Publish to NPM.')
  }
  triggers {
    issueCommentTrigger('(?i).*jenkins\\W+run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  stages {
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Static Analisis') {
      options { skipDefaultCheckout() }
      environment {
        HOME = "${env.WORKSPACE}"
      }
      steps {
        withGithubNotify(context: 'Lint') {
          deleteDir()
          unstash 'source'
          script {
            docker.image("node:${NODE_VERSION}-alpine").inside(){
              dir("${BASE_DIR}"){
                sh(label: 'Build NodeJS', script: 'yarn install')
                sh(label: 'Lint', script: 'yarn lint')
              }
            }
          }
          stash allowEmpty: true, name: 'compiledSource', useDefaultExcludes: false
        }
      }
    }
    stage('Build') {
      parallel {
        stage('OSX') {
          agent { label 'macosx' }
          options { skipDefaultCheckout() }
          environment {
            HOME = "${env.WORKSPACE}"
            JEST_JUNIT_OUTPUT_NAME="TEST-unit-osx.xml"
          }
          steps {
            withGithubNotify(context: 'OSX tests') {
              deleteDir()
              unstash 'source'
              script {
                docker.image("node:${NODE_VERSION}-alpine").inside(){
                  dir("${BASE_DIR}"){
                    sh(label: 'Yarn Install', script: 'yarn install')
                    sh(label: 'Yarn Build', script: 'yarn test:ci')
                  }
                }
              }
            }
          }
          post {
            always {
              junit(allowEmptyResults: true, keepLongStdio: true, testResults: "**/${JEST_JUNIT_OUTPUT_NAME}")
            }
          }
        }
        stage('Linux') {
          options { skipDefaultCheckout() }
          environment {
            HOME = "${env.WORKSPACE}"
            JEST_JUNIT_OUTPUT_NAME="TEST-unit-linux.xml"
          }
          steps {
            withGithubNotify(context: 'Linux tests') {
              deleteDir()
              unstash 'compiledSource'
              script {
                docker.image("node:${NODE_VERSION}-alpine").inside(){
                  dir("${BASE_DIR}"){
                    sh(label: 'Yarn Build', script: 'yarn test:ci')
                  }
                }
              }
            }
          }
          post {
            always {
              junit(allowEmptyResults: true, keepLongStdio: true, testResults: "**/${JEST_JUNIT_OUTPUT_NAME}")
            }
          }
        }
        stage('Windows') {
          agent { label 'windows-2019-immutable' }
          options { skipDefaultCheckout() }
          environment {
            PATH="${PATH};C:\\Program Files\\nodejs"
            JEST_JUNIT_OUTPUT_NAME="TEST-unit-windows.xml"
          }
          steps {
            deleteDir()
            unstash 'source'
            dir(BASE_DIR) {
              powershell label: 'Install tools', script: ".\\.ci\\scripts\\windows\\install-node.ps1"
              bat label: 'Tool versions', script: '''
                npm --version
                node --version
              '''
              bat label: 'NPM Install', script: 'npm install'
              bat label: 'NPM Tests', script: 'npm run test:ci:windows'
            }
          }
          post {
            always {
              junit(allowEmptyResults: true, keepLongStdio: true, testResults: "**/${JEST_JUNIT_OUTPUT_NAME}")
            }
          }
        }
      }
    }
    stage('Publish to NPM') {
      options { skipDefaultCheckout() }
      when {
        beforeAgent true
        allOf {
          tag pattern: 'v\\d+.*', comparator: 'REGEXP'
          expression { return params.PUBLISH_TO_NPM }
        }
      }
      steps {
        withGithubNotify(context: 'Publish to NPM') {
          deleteDir()
          unstash 'compiledSource'
          script {
            docker.image("node:10").inside(){
              dir("${BASE_DIR}") {
                sh(label: 'Lint', script: 'yarn pub')
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult()
    }
  }
}